"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Note: PyMySQL configuration is in backend/__init__.py
# It must be imported before Django loads the MySQL backend

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file in project root
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-@6zd(2ds4^@a*n9a^iivv)igyq+jp0yaqkw%)xk^cf5o*!+un4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # Token authentication
    'corsheaders',
    'api',
]

# Add channels if available (for WebSocket support)
try:
    import channels
    INSTALLED_APPS.append('channels')
except ImportError:
    pass  # Channels not installed, WebSocket features will be unavailable

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files
    'corsheaders.middleware.CorsMiddleware',  # Add top
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'backend.middleware.DatabaseConnectionCleanupMiddleware',  # Ensure DB connections are cleaned up
]

ROOT_URLCONF = 'backend.urls'



WSGI_APPLICATION = 'backend.wsgi.application'

# Django Channels configuration (only if channels is installed)
try:
    import channels
    ASGI_APPLICATION = 'backend.asgi.application'
    # Channel layers configuration (using in-memory for development)
    # For production, use Redis: 'channels_redis.core.RedisChannelLayer'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }
except ImportError:
    # Channels not installed, WebSocket features unavailable
    pass


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

CORS_ALLOWED_ORIGINS = ['http://localhost:3000']  # For dev React
CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be sent with requests (needed for CSRF token)

# Database configuration
# Use SQLite for development if USE_SQLITE is set, otherwise use MySQL
use_sqlite = os.getenv('USE_SQLITE', 'False').lower() == 'true'

if use_sqlite:
    # SQLite database for development/testing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # MySQL database configuration
    # Parse DB_HOST to handle cases where port is included (e.g., "localhost:5506")
    db_host = os.getenv('DB_HOST', 'localhost')
    db_port = os.getenv('DB_PORT', '3306')

    # If DB_HOST contains a port (format: "host:port"), extract it
    if ':' in db_host:
        db_host, db_port = db_host.split(':', 1)
    
    # Convert localhost to 127.0.0.1 for Docker MySQL (localhost uses socket, 127.0.0.1 uses TCP)
    # This is important when MySQL is in Docker and needs TCP/IP connection
    if db_host.strip().lower() == 'localhost':
        db_host = '127.0.0.1'

    # Strip whitespace from environment variables (common .env issue)
    db_name = os.getenv('DB_NAME', os.getenv('DB_DATABASE', 'novastoryteller')).strip()
    db_user = os.getenv('DB_USER', os.getenv('DB_USERNAME', 'myuser')).strip()
    db_password = os.getenv('DB_PASSWORD', 'mypassword').strip()
    db_host = db_host.strip()
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': {
                'charset': 'utf8mb4',
                # Connection pool settings to prevent too many connections
                'connect_timeout': 10,  # 10 seconds connection timeout
                'read_timeout': 30,  # 30 seconds read timeout
                'write_timeout': 30,  # 30 seconds write timeout
                # Set session variables to limit connection usage and prevent connection leaks
                # Keep it simple - only essential settings that MySQL definitely supports
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
            # Use connection pooling: keep connections alive for 300 seconds (5 minutes)
            # This reduces the number of new connections while preventing stale connections
            'CONN_MAX_AGE': 300,  # 5 minutes - balance between reuse and freshness
            'AUTOCOMMIT': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files directories
# Include React build directory so assets can be served
STATICFILES_DIRS = []
static_build_dir = BASE_DIR / 'static/build'
if static_build_dir.exists():
    STATICFILES_DIRS.append(static_build_dir)

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Templates directory
            BASE_DIR / 'static/build',  # React build directory
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Session configuration for WebSocket authentication
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cookies to be sent with WebSocket connections
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
