# Generated by Django 6.0 on 2026-01-05 23:14

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faqcategory_newscategory_faq_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Category',
                'verbose_name_plural': 'Page Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image (max 50KB)', null=True, upload_to=api.models.news_image_upload_path),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Page content (rich text)')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image (max 50KB)', null=True, upload_to=api.models.page_image_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this page on homepage')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this page has been viewed')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date and time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pages', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='api.pagecategory')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_page_created_e089ed_idx'), models.Index(fields=['status', '-published_at'], name='api_page_status_e60a6a_idx'), models.Index(fields=['category', '-created_at'], name='api_page_categor_1d276a_idx'), models.Index(fields=['slug'], name='api_page_slug_a996d5_idx')],
            },
        ),
    ]
