# Generated by Django 6.0 on 2026-01-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, unique=True),
        ),
    ]
