# Generated by Django 6.0 on 2026-01-16 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_plan_subscription_invoice_with_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove features field from Subscription if it exists (may have been removed in previous migration)
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'api_subscription' 
                    AND column_name = 'features');
                SET @sql = IF(@exists > 0, 
                    'ALTER TABLE api_subscription DROP COLUMN features',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.plan'),
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('analysis_type', models.CharField(choices=[('pillbox', 'Pillbox Identification'), ('fine_print', 'Fine Print Reader'), ('document', 'Document Scanner & Fraud Detection')], max_length=20)),
                ('image', models.ImageField(help_text='Uploaded image', upload_to='eagleview/analyses/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw Gemini API response')),
                ('analysis_text', models.TextField(blank=True, help_text='Processed analysis text')),
                ('summary', models.TextField(blank=True, help_text='Summary of analysis')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0-1)', null=True)),
                ('pillbox_data', models.JSONField(blank=True, default=dict, help_text='Pillbox compartment data')),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text from fine print')),
                ('fraud_flags', models.JSONField(blank=True, default=list, help_text='List of fraud detection flags')),
                ('document_info', models.JSONField(blank=True, default=dict, help_text='Document classification and key info')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Analysis',
                'verbose_name_plural': 'Image Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('pillbox_empty', 'Pillbox Compartment Empty'), ('pillbox_missed', 'Missed Medication'), ('fraud_detected', 'Fraud Detected'), ('document_urgent', 'Urgent Document'), ('analysis_failed', 'Analysis Failed'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(blank=True, help_text='Specific caregiver to notify (null = all caregivers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_alerts', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(help_text='The senior user this alert is about', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('related_analysis', models.ForeignKey(blank=True, help_text='Related image analysis if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.imageanalysis')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PillboxSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('compartment_label', models.CharField(help_text="Compartment label (e.g., 'Mon AM')", max_length=50)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('medication_name', models.CharField(blank=True, help_text='Name of medication', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='Dosage information', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillbox_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pillbox Schedule',
                'verbose_name_plural': 'Pillbox Schedules',
                'ordering': ['day_of_week', 'time_of_day'],
            },
        ),
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_senior', models.BooleanField(default=True, help_text='Mark user as a senior')),
                ('preferred_font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra-large', 'Extra Large')], default='medium', help_text='Preferred font size for accessibility', max_length=20)),
                ('high_contrast_mode', models.BooleanField(default=False, help_text='Enable high contrast mode')),
                ('voice_navigation_enabled', models.BooleanField(default=True, help_text='Enable voice navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(blank=True, help_text='Caregiver who created/manages this senior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_senior_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senior Profile',
                'verbose_name_plural': 'Senior Profiles',
            },
        ),
        migrations.CreateModel(
            name='CaregiverRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('family', 'Family Member'), ('caregiver', 'Professional Caregiver'), ('friend', 'Friend'), ('other', 'Other')], default='family', help_text='Type of relationship', max_length=50)),
                ('can_view_alerts', models.BooleanField(default=True, help_text='Caregiver can view alerts')),
                ('can_view_dashboard', models.BooleanField(default=True, help_text='Caregiver can view dashboard')),
                ('can_manage_schedule', models.BooleanField(default=False, help_text='Caregiver can manage pillbox schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(help_text='The caregiver user', on_delete=django.db.models.deletion.CASCADE, related_name='managed_seniors', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(help_text='The senior user being managed', on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver Relationship',
                'verbose_name_plural': 'Caregiver Relationships',
                'indexes': [models.Index(fields=['caregiver', '-created_at'], name='api_caregiv_caregiv_1877d9_idx'), models.Index(fields=['senior', '-created_at'], name='api_caregiv_senior__6af7dd_idx')],
                'unique_together': {('caregiver', 'senior')},
            },
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['user', '-created_at'], name='api_imagean_user_id_3624ae_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['analysis_type', '-created_at'], name='api_imagean_analysi_b31112_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['status', '-created_at'], name='api_imagean_status_946dec_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['senior', '-created_at'], name='api_alert_senior__af2072_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['caregiver', '-created_at'], name='api_alert_caregiv_d5fec2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read', '-created_at'], name='api_alert_is_read_e4e908_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', '-created_at'], name='api_alert_priorit_61a11f_idx'),
        ),
        migrations.AddIndex(
            model_name='pillboxschedule',
            index=models.Index(fields=['user', 'day_of_week', 'time_of_day'], name='api_pillbox_user_id_5cddff_idx'),
        ),
        migrations.AddIndex(
            model_name='seniorprofile',
            index=models.Index(fields=['caregiver', '-created_at'], name='api_seniorp_caregiv_a7dab5_idx'),
        ),
    ]
