# Generated by Django 6.0

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_caregiver_to_senior_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Story title', max_length=200)),
                ('prompt', models.TextField(help_text="User's initial story prompt")),
                ('story_text', models.TextField(blank=True, help_text='Generated story text from Nova AI')),
                ('template', models.CharField(choices=[('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('mystery', 'Mystery'), ('educational', 'Educational')], default='adventure', help_text='Story template type', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional uploaded image for story', null=True, upload_to='stories/images/')),
                ('image_description', models.TextField(blank=True, help_text='AI-generated image description from Titan Embeddings')),
                ('audio_file', models.FileField(blank=True, help_text='Generated audio file from Nova 2 Sonic', null=True, upload_to='stories/audio/')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the story is published/public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this story', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', '-created_at'], name='api_story_user_id_created_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['template', '-created_at'], name='api_story_template_created_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_published', '-created_at'], name='api_story_is_publ_created_idx'),
        ),
    ]

