# Generated by Django 6.0 on 2026-02-07 23:13

import api.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Conditionally create StorySession table if it doesn't exist
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_storysession');
                SET @sql = IF(@exists = 0,
                    'CREATE TABLE api_storysession (
                        id CHAR(36) NOT NULL PRIMARY KEY,
                        started_at DATETIME(6) NOT NULL,
                        ended_at DATETIME(6) NULL,
                        duration_seconds INTEGER NULL,
                        completed BOOLEAN NOT NULL DEFAULT 0,
                        created_at DATETIME(6) NOT NULL,
                        updated_at DATETIME(6) NOT NULL
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="DROP TABLE IF EXISTS api_storysession;",
            state_operations=[
                migrations.CreateModel(
                    name='StorySession',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the listening session started')),
                        ('ended_at', models.DateTimeField(blank=True, help_text='When the listening session ended', null=True)),
                        ('duration_seconds', models.IntegerField(blank=True, help_text='Duration of the session in seconds', null=True)),
                        ('completed', models.BooleanField(default=False, help_text='Whether the story was listened to completion')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Story Session',
                        'verbose_name_plural': 'Story Sessions',
                        'ordering': ['-started_at'],
                    },
                ),
            ],
        ),
        # Conditionally remove indexes from models that are being deleted
        # These operations are safe to skip if indexes don't exist
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveIndex(
                    model_name='alert',
                    name='api_alert_senior__af2072_idx',
                ),
                migrations.RemoveIndex(
                    model_name='alert',
                    name='api_alert_caregiv_d5fec2_idx',
                ),
                migrations.RemoveIndex(
                    model_name='alert',
                    name='api_alert_is_read_e4e908_idx',
                ),
                migrations.RemoveIndex(
                    model_name='alert',
                    name='api_alert_priorit_61a11f_idx',
                ),
                migrations.AlterUniqueTogether(
                    name='caregiverrelationship',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='caregiverrelationship',
                    name='api_caregiv_caregiv_1877d9_idx',
                ),
                migrations.RemoveIndex(
                    model_name='caregiverrelationship',
                    name='api_caregiv_senior__6af7dd_idx',
                ),
                migrations.RemoveIndex(
                    model_name='imageanalysis',
                    name='api_imagean_user_id_3624ae_idx',
                ),
                migrations.RemoveIndex(
                    model_name='imageanalysis',
                    name='api_imagean_analysi_b31112_idx',
                ),
                migrations.RemoveIndex(
                    model_name='imageanalysis',
                    name='api_imagean_status_946dec_idx',
                ),
                migrations.RemoveIndex(
                    model_name='pillboxschedule',
                    name='api_pillbox_user_id_5cddff_idx',
                ),
                migrations.RemoveIndex(
                    model_name='seniorprofile',
                    name='api_seniorp_caregiv_a7dab5_idx',
                ),
            ],
        ),
        # Conditionally rename indexes on Story model
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_story'
                    AND INDEX_NAME = 'api_story_user_id_created_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE api_story RENAME INDEX api_story_user_id_created_idx TO api_story_user_id_5fb8c1_idx',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_story'
                    AND INDEX_NAME = 'api_story_template_created_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE api_story RENAME INDEX api_story_template_created_idx TO api_story_templat_bdee67_idx',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_story'
                    AND INDEX_NAME = 'api_story_is_publ_created_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE api_story RENAME INDEX api_story_is_publ_created_idx TO api_story_is_publ_b859bc_idx',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RenameIndex(
                    model_name='story',
                    new_name='api_story_user_id_5fb8c1_idx',
                    old_name='api_story_user_id_created_idx',
                ),
                migrations.RenameIndex(
                    model_name='story',
                    new_name='api_story_templat_bdee67_idx',
                    old_name='api_story_template_created_idx',
                ),
                migrations.RenameIndex(
                    model_name='story',
                    new_name='api_story_is_publ_b859bc_idx',
                    old_name='api_story_is_publ_created_idx',
                ),
            ],
        ),
        # Conditionally remove 'features' field if it exists
        # Using RunSQL with conditional check to avoid error if column doesn't exist
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_subscription'
                    AND COLUMN_NAME = 'features');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE api_subscription DROP COLUMN features',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name='subscription',
                    name='features',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional uploaded image for story (stored in stories/YYYY/MM/)', null=True, upload_to=api.utils.story_image_upload_path),
        ),
        migrations.AddField(
            model_name='storysession',
            name='story',
            field=models.ForeignKey(help_text='Story that was listened to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.story'),
        ),
        migrations.AddField(
            model_name='storysession',
            name='user',
            field=models.ForeignKey(help_text='User who listened to the story', on_delete=django.db.models.deletion.CASCADE, related_name='story_sessions', to=settings.AUTH_USER_MODEL),
        ),
        # Conditionally remove fields from models being deleted
        # These are safe to skip if tables don't exist
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name='alert',
                    name='caregiver',
                ),
                migrations.RemoveField(
                    model_name='alert',
                    name='related_analysis',
                ),
                migrations.RemoveField(
                    model_name='alert',
                    name='senior',
                ),
                migrations.RemoveField(
                    model_name='caregiverrelationship',
                    name='caregiver',
                ),
                migrations.RemoveField(
                    model_name='caregiverrelationship',
                    name='senior',
                ),
                migrations.RemoveField(
                    model_name='imageanalysis',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='pillboxschedule',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='seniorprofile',
                    name='caregiver',
                ),
                migrations.RemoveField(
                    model_name='seniorprofile',
                    name='user',
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='storysession',
            index=models.Index(fields=['user', '-started_at'], name='api_storyse_user_id_5edd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='storysession',
            index=models.Index(fields=['story', '-started_at'], name='api_storyse_story_i_836861_idx'),
        ),
        migrations.AddIndex(
            model_name='storysession',
            index=models.Index(fields=['-started_at'], name='api_storyse_started_28aaaa_idx'),
        ),
        # Conditionally delete models - only if tables exist
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_alert');
                SET @sql = IF(@exists > 0, 'DROP TABLE IF EXISTS api_alert', 'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_caregiverrelationship');
                SET @sql = IF(@exists > 0, 'DROP TABLE IF EXISTS api_caregiverrelationship', 'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_imageanalysis');
                SET @sql = IF(@exists > 0, 'DROP TABLE IF EXISTS api_imageanalysis', 'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_pillboxschedule');
                SET @sql = IF(@exists > 0, 'DROP TABLE IF EXISTS api_pillboxschedule', 'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_seniorprofile');
                SET @sql = IF(@exists > 0, 'DROP TABLE IF EXISTS api_seniorprofile', 'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.DeleteModel(
                    name='Alert',
                ),
                migrations.DeleteModel(
                    name='CaregiverRelationship',
                ),
                migrations.DeleteModel(
                    name='ImageAnalysis',
                ),
                migrations.DeleteModel(
                    name='PillboxSchedule',
                ),
                migrations.DeleteModel(
                    name='SeniorProfile',
                ),
            ],
        ),
    ]
