# Generated by Django 6.0 on 2026-02-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='voice_id',
            field=models.CharField(
                default='Joanna',
                help_text='Amazon Polly voice ID for narration (e.g., Joanna, Matthew, Ivy)',
                max_length=50
            ),
        ),
    ]

