# Generated by Django 6.0 on 2026-02-09 03:31

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_story_voice_id'),
    ]

    operations = [
        # Conditionally rename first index if it exists
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_playlist'
                    AND INDEX_NAME = 'api_playli_user_id_created_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE `api_playlist` RENAME INDEX `api_playli_user_id_created_idx` TO `api_playlis_user_id_5deead_idx`',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_playlist'
                    AND INDEX_NAME = 'api_playlis_user_id_5deead_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE `api_playlist` RENAME INDEX `api_playlis_user_id_5deead_idx` TO `api_playli_user_id_created_idx`',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            state_operations=[
                migrations.RenameIndex(
                    model_name='playlist',
                    new_name='api_playlis_user_id_5deead_idx',
                    old_name='api_playli_user_id_created_idx',
                ),
            ],
        ),
        # Conditionally rename second index if it exists
        migrations.RunSQL(
            sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_playlist'
                    AND INDEX_NAME = 'api_playli_is_publ_created_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE `api_playlist` RENAME INDEX `api_playli_is_publ_created_idx` TO `api_playlis_is_publ_ac3b21_idx`',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
                SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'api_playlist'
                    AND INDEX_NAME = 'api_playlis_is_publ_ac3b21_idx');
                SET @sql = IF(@exists > 0,
                    'ALTER TABLE `api_playlist` RENAME INDEX `api_playlis_is_publ_ac3b21_idx` TO `api_playli_is_publ_created_idx`',
                    'SELECT 1');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            state_operations=[
                migrations.RenameIndex(
                    model_name='playlist',
                    new_name='api_playlis_is_publ_ac3b21_idx',
                    old_name='api_playli_is_publ_created_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Generated audio file from Nova 2 Sonic (stored in YYYY/MM/<story-id>/)', null=True, upload_to=api.utils.story_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional uploaded image for story (stored in YYYY/MM/<story-id>/)', null=True, upload_to=api.utils.story_image_upload_path),
        ),
    ]
