# Generated by Django 6.0 on 2026-02-09 10:53:05

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_api_playli_user_id_created_idx_api_playlis_user_id_5deead_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_text', models.TextField(help_text='Story text at this revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_revisions', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(help_text='Story this revision belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.story')),
            ],
            options={
                'verbose_name': 'Story Revision',
                'verbose_name_plural': 'Story Revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storyrevision',
            index=models.Index(fields=['story', '-created_at'], name='story_rev_story_created_idx'),
        ),
    ]

