# Generated by Django 6.0 on 2026-02-09 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_storyrevision_20260209_105305'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('3-5', '3-5 years (Simple tales, 200-300 words)'), ('6-8', '6-8 years (Adventures with lessons, 400-500 words)'), ('9-12', '9-12 years (Complex plots, 600-700 words)')], default='6-8', help_text='Target age range for stories (affects length and complexity)', max_length=10)),
                ('genre_preference', models.CharField(choices=[('fantasy', 'Fantasy'), ('adventure', 'Adventure'), ('sci-fi', 'Science Fiction'), ('mystery', 'Mystery'), ('educational', 'Educational'), ('mixed', 'Mixed (Fantasy, Adventure, Real-world)')], default='mixed', help_text='Preferred genre mix for stories', max_length=20)),
                ('language_level', models.CharField(choices=[('simple', 'Simple (Basic words, short sentences)'), ('moderate', 'Moderate (Some complexity, explain new words)'), ('advanced', 'Advanced (Rich vocabulary, complex sentences)')], default='moderate', help_text='Language complexity level', max_length=20)),
                ('moral_theme', models.CharField(choices=[('friendship', 'Friendship'), ('kindness', 'Kindness'), ('bravery', 'Bravery'), ('curiosity', 'Curiosity'), ('teamwork', 'Teamwork'), ('growth', 'Growth & Learning'), ('empathy', 'Empathy'), ('mixed', 'Mixed (Various positive themes)')], default='mixed', help_text='Preferred moral themes in stories', max_length=20)),
                ('include_diversity', models.BooleanField(default=True, help_text='Include diverse characters from different backgrounds and abilities')),
                ('include_sensory_details', models.BooleanField(default=True, help_text='Add sensory details (sights, sounds) to make stories more engaging')),
                ('include_interactive_questions', models.BooleanField(default=True, help_text='Add questions mid-story to pause for user input')),
                ('max_word_count', models.IntegerField(default=800, help_text='Maximum word count for stories (default: 800)')),
                ('story_parts', models.IntegerField(default=5, help_text='Number of story parts/sections (default: 5, range: 3-8)')),
                ('include_sound_effects', models.BooleanField(default=True, help_text="Include sound effects in stories (e.g., 'Whoosh!', 'Bang!')")),
                ('explain_complex_words', models.BooleanField(default=True, help_text='Explain complex words in simple terms for younger readers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='story_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Story Settings',
                'verbose_name_plural': 'User Story Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
