# Generated by Django 6.0 on 2026-02-09 22:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userstorysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_number', models.IntegerField(help_text='Scene number/order (1, 2, 3, etc.)')),
                ('scene_text', models.TextField(help_text='Text content for this scene (extracted from story transcript)')),
                ('image', models.ImageField(blank=True, help_text='Generated portrait image for this scene (stored in YYYY/MM/<story-id>/scenes/)', null=True, upload_to=api.utils.story_scene_image_upload_path)),
                ('prompt_used', models.TextField(blank=True, help_text='Image generation prompt used to create this scene')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(help_text='Story this scene belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='api.story')),
            ],
            options={
                'verbose_name': 'Story Scene',
                'verbose_name_plural': 'Story Scenes',
                'ordering': ['story', 'scene_number'],
                'indexes': [
                    models.Index(fields=['story', 'scene_number'], name='api_storysc_story_n_123456_idx'),
                ],
                'unique_together': {('story', 'scene_number')},
            },
        ),
    ]

